# To install the git pre-commit hooks run:
#   prek install --install-hooks --overwrite
# To update the versions:
#   prek autoupdate
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
# Note the order is intentional to avoid multiple passes of the hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        # Using --unsafe-fixes can change code behavior
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v0.9.16
    hooks:
      - id: tombi-format
        # args: [ "--offline" ]
      - id: tombi-lint
        # args: [ "--offline" ]
    # Should you use this offline, uncomment those args
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: debug-statements
